import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

export const locales = ['en', 'fr', 'it'] as const
export type Locale = (typeof locales)[number]
export function localeFromPath(pathname: string): Locale {
  const candidate = pathname.split('/')[1]
  return locales.includes(candidate as Locale) ? candidate as Locale : 'en'
}

const common = {
  en: { seo: { title: 'Key Recorder — Measure observations, locally', description: 'A focused macOS instrument for short, controlled behavioral observations. Measure one to seven events, export a clear CSV, keep your data local.' }, nav: { label: 'Main navigation', researchers: 'For researchers', privacy: 'Privacy', download: 'Download', cta: 'Get Key Recorder' }, language: { label: 'Choose language' }, landing: { title: 'Choose your language' }, common: { backHome: 'Back to home', skip: 'Skip to content', enlarge: 'Open full-size screenshot', download: 'Download the DMG on GitHub', downloadNote: 'Free and open source. The DMG is ad hoc signed, not notarized by Apple. macOS may display a warning on first launch.', keys: '1–7 configurable keys', local: 'Stored on your Mac', format: 'CSV, ready for analysis' }, footer: { tagline: 'A quiet instrument for precise observations.', support: 'Buy me a coffee', license: 'Open source · MIT License' } },
  fr: { seo: { title: 'Key Recorder — Mesurer les observations, localement', description: 'Un instrument macOS ciblé pour les observations comportementales courtes et contrôlées. Mesurez de un à sept événements, exportez un CSV clair, gardez vos données localement.' }, nav: { label: 'Navigation principale', researchers: 'Pour les chercheurs', privacy: 'Confidentialité', download: 'Télécharger', cta: 'Obtenir Key Recorder' }, language: { label: 'Choisir la langue' }, landing: { title: 'Choisissez votre langue' }, common: { backHome: 'Retour à l’accueil', skip: 'Aller au contenu', enlarge: 'Ouvrir la capture en grand', download: 'Télécharger le DMG sur GitHub', downloadNote: 'Gratuit et open source. Le DMG est signé ad hoc, sans notarisation Apple. macOS peut afficher un avertissement au premier lancement.', keys: '1 à 7 touches configurables', local: 'Conservé sur votre Mac', format: 'CSV prêt à analyser' }, footer: { tagline: 'Un instrument discret pour des observations précises.', support: 'Offrir un café', license: 'Open source · Licence MIT' } },
  it: { seo: { title: 'Key Recorder — Misura le osservazioni, localmente', description: 'Uno strumento macOS essenziale per osservazioni comportamentali brevi e controllate. Misura da uno a sette eventi, esporta un CSV chiaro, conserva i dati localmente.' }, nav: { label: 'Navigazione principale', researchers: 'Per i ricercatori', privacy: 'Privacy', download: 'Scarica', cta: 'Ottieni Key Recorder' }, language: { label: 'Scegli la lingua' }, landing: { title: 'Scegli la tua lingua' }, common: { backHome: 'Torna alla home', skip: 'Vai al contenuto', enlarge: 'Apri la schermata a grandezza naturale', download: 'Scarica il DMG da GitHub', downloadNote: 'Gratuito e open source. Il DMG ha una firma ad hoc, senza notarizzazione Apple. macOS può mostrare un avviso al primo avvio.', keys: 'Da 1 a 7 tasti configurabili', local: 'Conservato sul tuo Mac', format: 'CSV pronto per l’analisi' }, footer: { tagline: 'Uno strumento discreto per osservazioni precise.', support: 'Offrimi un caffè', license: 'Open source · Licenza MIT' } }
}

const home = {
  en: { home: { eyebrow: 'MACOS / FIELD INSTRUMENT', hero: { title: 'Measure the moment.', emphasis: 'Keep the record.', body: 'Assign up to seven keys to the events you observe. Hold a key while an event happens. Get durations in a CSV, saved on your Mac.', cta: 'Download for macOS', secondary: 'See how it works', requirement: 'macOS 15.1 or later · No account required' }, screenshot: { alt: 'Key Recorder configuration window with two configured observation events.', caption: 'Example configuration with two events. Screenshot of the earlier interface.' }, statement: 'For researchers who need a reliable signal, not another complicated system.', featuresEyebrow: 'WHY KEY RECORDER', featuresTitle: 'From observation to CSV, in three steps.', features: { 1: { title: 'Choose one to seven events', body: 'Map your physical keys to the moments you need to observe: a dispenser, a lever, a choice, a response.' }, 2: { title: 'Record the duration', body: 'Hold a configured key while the event occurs. Live values make the observation easy to follow.' }, 3: { title: 'Take the CSV with you', body: 'Export interval-based durations that open cleanly in a spreadsheet, R, Python or your existing lab workflow.' } }, protocol: { aria: 'Example observation protocol', label: 'LIVE PROTOCOL / EXAMPLE', status: 'READY', keyA: 'Food dispenser', keyB: 'Lever', duration: 'duration', interval: 'interval', recording: 'LOCAL · RECORDING' }, example: { eyebrow: 'A REAL PROTOCOL', title: 'The data stays legible.', body: 'A good observation ends with a file you can understand. Every row is an interval. Every value is a duration in seconds. Nothing is hidden behind a proprietary dashboard.', link: 'Read the researcher guide', csv: { interval: 'Interval' }, caption: 'Duration in seconds · example data' }, download: { eyebrow: 'READY WHEN YOU ARE', title: 'Make the next observation count.', cta: 'Download the latest release' } } },
  fr: { home: { eyebrow: 'MACOS / INSTRUMENT DE TERRAIN', hero: { title: 'Mesurez l’instant.', emphasis: 'Gardez la trace.', body: 'Associez jusqu’à sept touches aux événements observés. Maintenez une touche pendant l’événement. Retrouvez les durées dans un CSV, sur votre Mac.', cta: 'Télécharger pour macOS', secondary: 'Voir comment ça marche', requirement: 'macOS 15.1 ou ultérieur · Aucun compte requis' }, screenshot: { alt: 'Fenêtre de configuration de Key Recorder avec deux événements d’observation configurés.', caption: 'Exemple de configuration à deux événements. Capture de l’ancienne interface.' }, statement: 'Pour les chercheurs qui ont besoin d’un signal fiable, pas d’un système de plus.', featuresEyebrow: 'POURQUOI KEY RECORDER', featuresTitle: 'De l’observation au CSV, en trois étapes.', features: { 1: { title: 'Choisissez de un à sept événements', body: 'Associez vos touches physiques aux moments à observer : un distributeur, un levier, un choix, une réponse.' }, 2: { title: 'Mesurez la durée', body: 'Maintenez une touche configurée pendant l’événement. Les valeurs en direct rendent l’observation facile à suivre.' }, 3: { title: 'Emportez le CSV', body: 'Exportez des durées par intervalle, compatibles avec un tableur, R, Python ou votre flux de laboratoire.' } }, protocol: { aria: 'Exemple de protocole d’observation', label: 'PROTOCOLE EN DIRECT / EXEMPLE', status: 'PRÊT', keyA: 'Distributeur', keyB: 'Levier', duration: 'durée', interval: 'intervalle', recording: 'LOCAL · ENREGISTREMENT' }, example: { eyebrow: 'UN PROTOCOLE RÉEL', title: 'Les données restent lisibles.', body: 'Une bonne observation se termine par un fichier compréhensible. Chaque ligne est un intervalle. Chaque valeur est une durée en secondes. Rien n’est caché derrière un tableau de bord propriétaire.', link: 'Lire le guide chercheur', csv: { interval: 'Intervalle' }, caption: 'Durée en secondes · données d’exemple' }, download: { eyebrow: 'PRÊT QUAND VOUS L’ÊTES', title: 'Donnez de la valeur à la prochaine observation.', cta: 'Télécharger la dernière version' } } },
  it: { home: { eyebrow: 'MACOS / STRUMENTO DA CAMPO', hero: { title: 'Misura l’istante.', emphasis: 'Conserva il dato.', body: 'Associa fino a sette tasti agli eventi da osservare. Tieni premuto un tasto durante l’evento. Ritrova le durate in un CSV, sul tuo Mac.', cta: 'Scarica per macOS', secondary: 'Scopri come funziona', requirement: 'macOS 15.1 o successivo · Nessun account richiesto' }, screenshot: { alt: 'Finestra di configurazione di Key Recorder con due eventi di osservazione configurati.', caption: 'Esempio di configurazione con due eventi. Schermata dell’interfaccia precedente.' }, statement: 'Per i ricercatori che hanno bisogno di un segnale affidabile, non di un altro sistema complesso.', featuresEyebrow: 'PERCHÉ KEY RECORDER', featuresTitle: 'Dall’osservazione al CSV, in tre passi.', features: { 1: { title: 'Scegli da uno a sette eventi', body: 'Associa i tuoi tasti fisici ai momenti da osservare: un distributore, una leva, una scelta, una risposta.' }, 2: { title: 'Registra la durata', body: 'Tieni premuto un tasto configurato durante l’evento. I valori in tempo reale rendono l’osservazione semplice da seguire.' }, 3: { title: 'Porta con te il CSV', body: 'Esporta durate divise per intervallo, leggibili in un foglio di calcolo, R, Python o nel tuo flusso di laboratorio.' } }, protocol: { aria: 'Esempio di protocollo di osservazione', label: 'PROTOCOLLO LIVE / ESEMPIO', status: 'PRONTO', keyA: 'Distributore', keyB: 'Leva', duration: 'durata', interval: 'intervallo', recording: 'LOCALE · REGISTRAZIONE' }, example: { eyebrow: 'UN PROTOCOLLO REALE', title: 'I dati restano leggibili.', body: 'Una buona osservazione termina con un file comprensibile. Ogni riga è un intervallo. Ogni valore è una durata in secondi. Nulla è nascosto dietro una dashboard proprietaria.', link: 'Leggi la guida per ricercatori', csv: { interval: 'Intervallo' }, caption: 'Durata in secondi · dati di esempio' }, download: { eyebrow: 'PRONTO QUANDO LO SEI', title: 'Dai valore alla prossima osservazione.', cta: 'Scarica l’ultima versione' } } }
}

const useCases = {
  en: { useCases: { homeEyebrow: 'USE CASES', homeTitle: 'Built for the moments you need to measure.', readMore: 'Read the use case', observation: { eyebrow: 'USE CASE / BEHAVIORAL OBSERVATION', title: 'A clear tool for controlled behavioral observation.', intro: 'Mark when your events happen, keep the measurement local, and leave the interpretation in your own research workflow.', sections: { 1: { title: 'Define the observed events', body: 'Name one to seven events in plain language and map them to physical keys. A dispenser, a lever, a response or any other moment your protocol needs.' }, 2: { title: 'Run a focused session', body: 'Set the duration and interval, start the session, and hold a key while its event occurs. The live values keep the operator oriented.' }, 3: { title: 'Preserve the context', body: 'Export the collected durations as CSV and keep the file beside your protocol notes and experiment metadata.' } }, cta: 'See download requirements' }, csv: { eyebrow: 'USE CASE / CSV EXPORT', title: 'From keyboard signal to usable CSV.', intro: 'Key Recorder produces a small, legible file that can move directly into a spreadsheet, R, Python or a lab archive.', sections: { 1: { title: 'One row, one interval', body: 'Each row represents an analysis interval, with durations in seconds for each configured event.' }, 2: { title: 'No proprietary dashboard', body: 'The result is a plain CSV you can inspect, version, share and process with the tools your team already uses.' }, 3: { title: 'Local from start to finish', body: 'The session is recorded on your Mac and exported where you choose. The website and app do not create a cloud data path.' } }, cta: 'See download requirements' } } },
  fr: { useCases: { homeEyebrow: 'CAS D’USAGE', homeTitle: 'Conçu pour les instants à mesurer.', readMore: 'Lire le cas d’usage', observation: { eyebrow: 'CAS D’USAGE / OBSERVATION COMPORTEMENTALE', title: 'Un outil clair pour une observation comportementale contrôlée.', intro: 'Signalez quand vos événements se produisent, gardez la mesure localement et conservez l’interprétation dans votre propre flux de recherche.', sections: { 1: { title: 'Définissez les événements observés', body: 'Nommez de un à sept événements simplement et associez-les à des touches physiques : un distributeur, un levier, une réponse ou tout autre moment du protocole.' }, 2: { title: 'Réalisez une session ciblée', body: 'Définissez la durée et l’intervalle, démarrez la session et maintenez une touche pendant l’événement. Les valeurs en direct guident l’opérateur.' }, 3: { title: 'Conservez le contexte', body: 'Exportez les durées collectées en CSV et conservez le fichier avec vos notes de protocole et métadonnées d’expérience.' } }, cta: 'Voir les prérequis de téléchargement' }, csv: { eyebrow: 'CAS D’USAGE / EXPORT CSV', title: 'Du signal clavier à un CSV exploitable.', intro: 'Key Recorder produit un fichier court et lisible, directement utilisable dans un tableur, R, Python ou une archive de laboratoire.', sections: { 1: { title: 'Une ligne, un intervalle', body: 'Chaque ligne représente un intervalle d’analyse, avec les durées en secondes de chaque événement configuré.' }, 2: { title: 'Aucun tableau de bord propriétaire', body: 'Le résultat est un CSV simple à inspecter, versionner, partager et traiter avec les outils de votre équipe.' }, 3: { title: 'Local du début à la fin', body: 'La session est enregistrée sur votre Mac et exportée où vous le souhaitez. L’app et le site ne créent pas de chemin de données cloud.' } }, cta: 'Voir les prérequis de téléchargement' } } },
  it: { useCases: { homeEyebrow: 'CASI D’USO', homeTitle: 'Progettato per i momenti da misurare.', readMore: 'Leggi il caso d’uso', observation: { eyebrow: 'CASO D’USO / OSSERVAZIONE COMPORTAMENTALE', title: 'Uno strumento chiaro per un’osservazione comportamentale controllata.', intro: 'Segnala quando accadono i tuoi eventi, conserva la misura localmente e lascia l’interpretazione al tuo flusso di ricerca.', sections: { 1: { title: 'Definisci gli eventi osservati', body: 'Assegna nomi chiari a un massimo di sette eventi e collegali a tasti fisici: un distributore, una leva, una risposta o qualsiasi momento del protocollo.' }, 2: { title: 'Esegui una sessione mirata', body: 'Imposta durata e intervallo, avvia la sessione e tieni premuto un tasto durante l’evento. I valori live aiutano l’operatore.' }, 3: { title: 'Conserva il contesto', body: 'Esporta le durate raccolte in CSV e conserva il file con le note del protocollo e i metadati dell’esperimento.' } }, cta: 'Vedi i requisiti di download' }, csv: { eyebrow: 'CASO D’USO / ESPORTAZIONE CSV', title: 'Dal segnale da tastiera a un CSV utilizzabile.', intro: 'Key Recorder produce un file breve e leggibile, pronto per un foglio di calcolo, R, Python o un archivio di laboratorio.', sections: { 1: { title: 'Una riga, un intervallo', body: 'Ogni riga rappresenta un intervallo di analisi, con le durate in secondi di ogni evento configurato.' }, 2: { title: 'Nessuna dashboard proprietaria', body: 'Il risultato è un CSV semplice da controllare, versionare, condividere ed elaborare con gli strumenti del tuo team.' }, 3: { title: 'Locale dall’inizio alla fine', body: 'La sessione viene registrata sul Mac ed esportata dove scegli. L’app e il sito non creano un percorso dati cloud.' } }, cta: 'Vedi i requisiti di download' } } }
}

const pages = {
  en: { researchers: { eyebrow: 'FOR RESEARCHERS', title: 'A simple protocol for a precise moment.', intro: 'Key Recorder is made for short, controlled observations where an operator needs to mark when any of up to seven events is happening.', prepare: { title: 'Prepare the protocol', body: 'Choose one to seven physical keys, give them meaningful names, set the observation duration and choose an interval that matches the precision your study needs.' }, record: { title: 'Run the observation', body: 'Start the session, hold a configured key while its event occurs, and follow the live duration values. Stop early when needed: the collected portion is still exported.' }, read: { title: 'Read the CSV', body: 'Each row represents an analysis interval. Values are durations in seconds, not interaction counts. Keep the CSV beside your experiment metadata and protocol notes.' } }, privacy: { eyebrow: 'LOCAL BY DESIGN', title: 'Your observation stays on your Mac.', intro: 'Key Recorder has no network service, no account and no analytics inside the application. It is deliberately small enough to inspect.', local: { title: 'No upload path', body: 'The application processes the configured signals locally and writes the result to a CSV file you choose. Your files remain under your own storage policy.' }, permissions: { title: 'Transparent permissions', body: 'Enable Input Monitoring in System Settings so the app can receive the configured keys during a recording. Accessibility is not required for passive recording. The app does not store what you type.' }, limits: { title: 'Know what is stored', body: 'Key Recorder measures durations, not interaction counts. Session titles, protocol notes and metadata you enter are saved in the local archive. It does not identify participants automatically.' } }, download: { eyebrow: 'INSTALLATION', title: 'A native Mac app, ready for the field.', intro: 'Download the latest public release, open the DMG and move Key Recorder to Applications.', requirements: { title: 'Requirements', body: 'macOS 15.1 or later, on Apple silicon or Intel. Enable Input Monitoring to record the configured keys.' }, install: { title: 'Install in a minute', body: 'Open the downloaded DMG, drag Key Recorder to Applications, launch it and follow the permission prompts in System Settings.' }, release: { title: 'Public, inspectable, reproducible', body: 'Key Recorder is open source under the MIT License. Releases and source code are published on GitHub.', link: 'Open GitHub Releases' } } },
  fr: { researchers: { eyebrow: 'POUR LES CHERCHEURS', title: 'Un protocole simple pour un instant précis.', intro: 'Key Recorder est conçu pour les observations courtes et contrôlées où un opérateur doit signaler quand l’un des événements configurés se produit, jusqu’à sept par session.', prepare: { title: 'Préparez le protocole', body: 'Choisissez de une à sept touches physiques, donnez-leur des noms explicites, définissez la durée d’observation et un intervalle adapté à la précision de votre étude.' }, record: { title: 'Réalisez l’observation', body: 'Démarrez la session, maintenez une touche pendant son événement et suivez les durées en direct. Arrêtez plus tôt si nécessaire : la portion collectée est exportée.' }, read: { title: 'Lisez le CSV', body: 'Chaque ligne représente un intervalle d’analyse. Les valeurs sont des durées en secondes, pas des nombres d’interactions. Conservez le CSV avec les métadonnées et les notes du protocole.' } }, privacy: { eyebrow: 'LOCAL PAR CONCEPTION', title: 'Votre observation reste sur votre Mac.', intro: 'Key Recorder n’a ni service réseau, ni compte, ni analytics dans l’application. Il est volontairement assez petit pour être inspecté.', local: { title: 'Aucun chemin d’envoi', body: 'L’application traite localement les signaux configurés et écrit le résultat dans le CSV de votre choix. Vos fichiers restent soumis à votre politique de stockage.' }, permissions: { title: 'Des permissions transparentes', body: 'Activez Surveillance de l’entrée dans Réglages Système pour recevoir les touches configurées pendant une session. L’autorisation Accessibilité n’est pas nécessaire à l’enregistrement passif. L’app ne conserve pas ce que vous tapez.' }, limits: { title: 'Ce qui est conservé', body: 'Key Recorder mesure des durées, pas des nombres d’interactions. Les titres, notes de protocole et métadonnées que vous saisissez sont conservés dans l’archive locale. L’app n’identifie pas automatiquement les participants.' } }, download: { eyebrow: 'INSTALLATION', title: 'Une app Mac native, prête pour le terrain.', intro: 'Téléchargez la dernière release publique, ouvrez le DMG et déplacez Key Recorder dans Applications.', requirements: { title: 'Prérequis', body: 'macOS 15.1 ou ultérieur, sur Apple silicon ou Intel. Activez Surveillance de l’entrée pour enregistrer les touches configurées.' }, install: { title: 'Installez en une minute', body: 'Ouvrez le DMG téléchargé, glissez Key Recorder dans Applications, lancez-le et suivez les demandes de permissions dans Réglages Système.' }, release: { title: 'Public, inspectable, reproductible', body: 'Key Recorder est open source sous licence MIT. Les releases et le code source sont publiés sur GitHub.', link: 'Ouvrir les releases GitHub' } } },
  it: { researchers: { eyebrow: 'PER I RICERCATORI', title: 'Un protocollo semplice per un momento preciso.', intro: 'Key Recorder è pensato per osservazioni brevi e controllate in cui un operatore deve segnalare quando si verifica uno degli eventi configurati, fino a sette per sessione.', prepare: { title: 'Prepara il protocollo', body: 'Scegli da uno a sette tasti fisici, assegna nomi chiari, imposta la durata dell’osservazione e scegli un intervallo coerente con la precisione del tuo studio.' }, record: { title: 'Esegui l’osservazione', body: 'Avvia la sessione, tieni premuto un tasto durante il relativo evento e segui i valori in tempo reale. Puoi fermarti prima: la parte raccolta viene comunque esportata.' }, read: { title: 'Leggi il CSV', body: 'Ogni riga rappresenta un intervallo di analisi. I valori sono durate in secondi, non conteggi di interazioni. Conserva il CSV con i metadati e le note del protocollo.' } }, privacy: { eyebrow: 'LOCALE PER SCELTA', title: 'La tua osservazione resta sul Mac.', intro: 'Key Recorder non ha servizi di rete, account o analytics nell’applicazione. È volutamente abbastanza piccolo da poter essere controllato.', local: { title: 'Nessun percorso di upload', body: 'L’applicazione elabora localmente i segnali configurati e scrive il risultato nel CSV che scegli. I tuoi file restano soggetti alla tua politica di archiviazione.' }, permissions: { title: 'Permessi trasparenti', body: 'Attiva Monitoraggio input nelle Impostazioni di Sistema per ricevere i tasti configurati durante una sessione. Accessibilità non è richiesta per la registrazione passiva. L’app non conserva ciò che digiti.' }, limits: { title: 'Cosa viene conservato', body: 'Key Recorder misura durate, non conteggi di interazioni. Titoli, note del protocollo e metadati che inserisci sono conservati nell’archivio locale. L’app non identifica automaticamente i partecipanti.' } }, download: { eyebrow: 'INSTALLAZIONE', title: 'Un’app Mac nativa, pronta per il campo.', intro: 'Scarica l’ultima release pubblica, apri il DMG e sposta Key Recorder in Applicazioni.', requirements: { title: 'Requisiti', body: 'macOS 15.1 o successivo, su Apple silicon o Intel. Attiva Monitoraggio input per registrare i tasti configurati.' }, install: { title: 'Installa in un minuto', body: 'Apri il DMG scaricato, trascina Key Recorder in Applicazioni, avvialo e segui le richieste di autorizzazione nelle Impostazioni di Sistema.' }, release: { title: 'Pubblico, ispezionabile, riproducibile', body: 'Key Recorder è open source con licenza MIT. Le release e il codice sorgente sono pubblicati su GitHub.', link: 'Apri le release GitHub' } } }
}

const resources = Object.fromEntries(locales.map((locale) => [locale, { translation: { ...common[locale], ...home[locale], ...useCases[locale], ...pages[locale] } }]))
void i18n.use(initReactI18next).init({ resources, lng: 'en', fallbackLng: 'en', interpolation: { escapeValue: false } })

export function getPageMeta(pathname: string) {
  const t = i18n.getFixedT(localeFromPath(pathname))
  const page = pathname.replace(/^\/(en|fr|it)/, '').replace(/\/$/, '')
  const key = ({
    '/researchers': 'researchers',
    '/privacy': 'privacy',
    '/download': 'download',
    '/use-cases/behavioral-observation': 'useCases.observation',
    '/use-cases/csv-export': 'useCases.csv',
  } as Record<string, string>)[page]
  return {
    title: key ? `${t(`${key}.title`)} — Key Recorder` : t('seo.title'),
    description: key ? t(`${key}.intro`) : t('seo.description'),
  }
}
export default i18n
